config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'customers#index'
  resources :customers
  resources :payments do
    collection do
      get 'success'
      get 'cancel'
    end
  end
  get '/delete_customer', to: 'customers#delete'   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Stripe::Customer.list(limit: 10)
  end

  def show
    @customer = Stripe::Customer.retrieve(params[:id])
  end

  def edit
    @customer = Stripe::Customer.retrieve(params[:id])
  end

  def create
    customer = Stripe::Customer.create(
      email: params[:email]
    )
  
    if customer.save
      redirect_to customers_path, notice: "Customer created successfully"
    else
      flash[:error] = "Failed to create customer"
      redirect_to new_customer_path
    end
  end
  

  def update
    if Stripe::Customer.update(params[:id], { email: params[:email] })
    redirect_to customer_path(params[:id])
    else
      flash[:error] = "Failed to update customer"
      redirect_to edit_customer_path(params[:id])
    end
  end
  

  def destroy
    customer = Stripe::Customer.retrieve(params[:id])
  
    if customer.delete
      redirect_to delete_customer_path
    else
      flash[:error] = "Failed to delete customer"
      redirect_to customers_path
    end
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include Stripe

  def new
    @payment = Payment.new
  end

  def create
    @amount = params[:amount]
    service = PaymentService.new(params)
    session = service.create_checkout_session(params[:product_name])
    redirect_to session.url

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path
  end

  def success
    # Handle successful payment
    # You can access the Checkout Session ID via params[:session_id]
    flash[:success] = "Payment successful!"
    redirect_to root_path
  end

  def cancel
    flash[:error] = "Payment cancelled."
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/delete.html.erb
<h1>Delete Customer</h1>
<p>Customer has been deleted successfully.</p>
<%= link_to "Back to Customers", customers_path, class: "btn btn-primary" %>

app/views/customers/edit.html.erb
<h1 class="mb-4">Edit Customer</h1>

<%= form_with url: customer_path(@customer.id), method: :put, class: "mb-4" do |form| %>
  <div class="form-group">
    <%= form.label :email, class: "font-weight-bold" %>
    <%= form.text_field :email, value: @customer.email, class: "form-control" %>
  </div>

  <%= form.submit "Save Changes", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back", customers_path, class: "btn btn-secondary" %>

app/views/customers/index.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>

<h1 class="mb-4">Customers</h1>

<div class="table-responsive mb-4">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Email</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= link_to customer.email, customer_path(customer.id) %></td>
  

          <td class="text-end">
            <%= link_to "Delete", customer_path(customer.id), method: :delete, data: { confirm: "Are you sure you want to delete this customer?" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Make Payment", new_payment_path, class: "btn btn-primary btn-sm" %>

app/views/customers/new.html.erb
<div class="container">
  <h1 class="mb-4">New Customer</h1>

  <%= form_with url: customers_path, method: :post, class: "mb-4" do |form| %>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <%= form.submit "Create Customer", class: "btn btn-primary" %>
  <% end %>

  <%= link_to "Back", customers_path, class: "btn btn-secondary" %>
</div>

app/views/customers/show.html.erb
<div class="container">
  <h1 class="my-5">Customer</h1>

  <div class="card mb-3">
    <div class="card-body">
      <p class="card-text"><strong>Email:</strong> <%= @customer.email %></p>
      <p class="card-text"><strong>ID:</strong> <%= @customer.id %></p>

      <div class="btn-group">
        <%= link_to "Edit", edit_customer_path(@customer.id), class: "btn btn-primary mr-2" %>
        <%= link_to "Back", customers_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeHome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <style>
  .border-main {
    max-width: 800px;
    margin: 0 auto;
    border: solid 4px #e9e9e9;
    padding: 20px 40px;
    margin-bottom: 30px;
  }
  </style>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-12 mt-3 border-main">
       <%= yield %>
       </div>
    </div>
    </div>
  </body>
</html>

app/views/payments/new.html.erb
<div class="main-section">
	<h2>Subscription</h2>	
	<div class="main-content">
		<%= form_tag payments_path do %>
			<article>
				<% if flash[:error].present? %>
					<div id="error_explanation">
						<p><%= flash[:error] %></p>
					</div>
				<% end %>
				<div class="product">
					<label>Product Name</label>
					<%= text_field_tag :product_name %>
				</div>
				<div class="amount">
					<label>Amount</label>
					<%= text_field_tag :amount %>
				</div>
			</article>
			<div class="button">
				<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
								data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
								data-description="<%= params[:product_name] %>"
								data-locale="auto">
				</script>
			</div>
		<% end %>
	</div>
</div>